<%
'
function Lang(Lang_str,Lang_idi)
	Dim str, idi, mMapPath
	str = ""&Lang_str
	idi = ""&Lang_idi
	
	if str = "" then
		Lang = ""
		exit function
	end if
	
	if idi = "" then
		mMapPath = replace(Server.MapPath("a"),"/","\")
		if inStr(mMapPath,"\esp\") >0 then 
			idi = "esp"
		elseif inStr(mMapPath,"\eng\") >0 then
			idi = "eng"
		elseif inStr(mMapPath,"\fra\") >0 then
			idi = "fra"
		elseif inStr(mMapPath,"\deu\") >0 then
			idi = "deu"
		end if
	end if

	select case idi
	case "esp"
		precio = "Precio"
		tipo = "Tipo"
		horas = "Horas"
		semana = "Semana"
		si = "Sí"
		no = "No"
		referencia = "Referencia"
		sexo = "Sexo"
		nombre = "Nombre"
		apellidos = "Apellidos"
		pais = "País"
		edad = "Edad"
		todos = "Todos"
		cp = "C.P."
		ciudad = "Ciudad"
		contacto = "Contacto"
		direccion = "Dirección"
		telefono = "Teléfono"
		fax = "Fax"
		puestosol = "Puesto"
		puestosofertados = "Puestos ofertados"
		lugarescolocacion = "Lugares de colocación"
		edadestudiantes = "Edad de los estudiantes"
		alumnosclase = "Nº de alumnos/ clase"
		comentarios = "Comentarios"
		datospersonales = "Datos personales"
		fechainicio = "Fecha de inicio"
		duracion = "Duración"
		remuneracion = "Remuneración"
		alojamiento = "Alojamiento"
		requisitos = "Requisitos"
		deseomasinfo = "Deseo recibir m&aacute;s informaci&oacute;n sobre Euro-Practice y sus ofertas"
		
		irportada = "Ir a Portada"
		ultimasofertas = "Últimas ofertas"
		ultimasofertas2 = "Últimas ofertas"
		ultimasofertas3 = "Últimas ofertas"
		nosecciones = "No hay secciones"
		textobuscar = "Texto a buscar"
		vertodas = "Ver todas"
		listadocompleto = "Listado completo"
		seltipotra = "Seleccione un tipo de trabajo"
		selpais = "Seleccione un país"

		sehanencontrado = "Se ha encontrado"
		sehanencontrado2 = "resultados en la búsqueda para"
		de = "de"
		fuente = "fuente"
		
		pagina = "Página"
		paginas = "Páginas"
		sabermas = "Saber más"
		sinresultados = "<b>Lo sentimos. No hemos encontrado resultados.</b>"
		
		espana = "España"
		portugal = "Portugal"
		francia = "Francia"
		alemania = "Alemania"
		irlanda = "Irlanda"
		reinounido = "Reino unido"
		inglaterra = "Inglaterra"
		austria = "Austria"
		escocia = "Escocia"
		italia = "Italia"
		
		espamol = "Español"
		ingles = "Inglés"
		frances = "Francés"
		aleman = "Alemán"
	case "eng"
		precio = "Precio"
		tipo = "Tipo"
		horas = "Horas"
		semana = "Semana"
		si = "Yes"
		no = "No"
		referencia = "Reference"
		sexo = "Sex"
		nombre = "Name"
		apellidos = "Address"
		pais = "Country"
		edad = "Age"
		todos = "All"
		cp = "P.C."
		ciudad = "City"
		contacto = "Contact"
		direccion = "Address"
		telefono = "Phone"
		fax = "Fax"
		puestosol = "Position"
		puestosofertados = "Postions offered"
		lugarescolocacion = "Locations"
		edadestudiantes = "Type of course"
		alumnosclase = "Type of accommodation"
		comentarios = "Comments"
		datospersonales = "Personal data"
		fechainicio = "Start date"
		duracion = "Duration"
		remuneracion = "Remuneration"
		alojamiento = "Accommodation"
		requisitos = "Requirements"
		
		deseomasinfo = "I desire to receive information about Euro-Practice and their offers."
		irportada = "Main"
		ultimasofertas = "Au-Pair agencies list"
		ultimasofertas2 = "International schools list"
		ultimasofertas3 = "Last offers"
		nosecciones = "No hay secciones"
		textobuscar = "Text to search"
		vertodas = "All"
		listadocompleto = "Full list"
		seltipotra = "Select a type of work"
		selpais = "Select a country"

		sehanencontrado = "Found"
		sehanencontrado2 = "results in the search for"
		de = "of"
		fuente = "source"
		
		pagina = "Page"
		paginas = "Pages"
		sabermas = "More info"
		sinresultados = "<b>sorry, there is no result</b>"
		
		espana = "Spain"
		portugal = "Portugal"
		francia = "France"
		alemania = "Germany"
		irlanda = "Ireland"
		reinounido = "United Kingdom"
		austria = "Austria"
		inglaterra = "England"
		escocia = "Scotland"
		italia = "Italy"
		
		espamol = "Spanish"
		ingles = "English"
		frances = "French"
		aleman = "German"
	case "fra"
		precio = "Precio"
		tipo = "Tipo"
		horas = "Horas"
		semana = "Semana"
		si = "Oui"
		no = "Non"
		referencia = "Reference"
		sexo = "Sexe"
		nombre = "Nom"
		apellidos = "Prenom"
		pais = "Pays"
		edad = "Áge"
		todos = "Tous"
		cp = "C.P."
		ciudad = "Ville"
		contacto = "Contact"
		direccion = "Adresse"
		telefono = "Téléphone"
		fax = "Télécopieur"
		puestosol = "Situation"
		puestosofertados = "Postes proposés"
		lugarescolocacion = "Localisations"
		edadestudiantes = "Types de cours"
		alumnosclase = "Hébergement"
		comentarios = "Commentaires"
		datospersonales = "Données personnelles"
		fechainicio = "Date de début"
		duracion = "Durée"
		remuneracion = "Rémunération"
		alojamiento = "Logement"
		requisitos = "Conditions"
		deseomasinfo = "Je désire recevoir des informations sur Euro Practice ainsi que les offres."
		irportada = "Home"
		ultimasofertas = "Liste d’agences"
		ultimasofertas2 = "Listes d’écoles internationales"
		ultimasofertas3 = "Offres de dernière minute"
		nosecciones = "No hay secciones"
		textobuscar = "Texte à rechercher"
		vertodas = "Toutes"
		listadocompleto = "Liste complète"
		seltipotra = "Choisissez un type de travail"
		selpais = "Choisissez un pays"

		sehanencontrado = "Trouvé"
		sehanencontrado2 = "résultats dans la recherche de"
		de = "de"
		fuente = "source"
		
		pagina = "Page"
		paginas = "Pages"
		sabermas = "+ d'infos"
		sinresultados = "<b>Désolé!.  Il n'y a pas des résultats.</b>"
		
		espana = "Espagne"
		portugal = "Portugal"
		francia = "France"
		alemania = "Allemagne"
		irlanda = "Irlande"
		reinounido = "Royaume Uni"
		inglaterra = "Angleterre"
		escocia = "Ecosse"
		austria = "Autriche"
		italia = "Italie"
		
		espamol = "Espagnol"
		ingles = "Anglais"
		frances = "Français"
		aleman = "Allemand"
	case "deu"
		precio = "Precio"
		tipo = "Tipo"
		horas = "Horas"
		semana = "Semana"
		si = "Ja"
		no = "Nein"
		referencia = "Hinweis"
		sexo = "Geschlecht"
		nombre = "Name"
		apellidos = "Familiename"
		pais = "Land"
		edad = "Alter"
		todos = "Alle"
		cp = "PLZ"
		ciudad = "Stadt"
		contacto = "Kontakt"
		direccion = "Adresse"
		telefono = "Telefon"
		fax = "Telefax"
		puestosol = "Platz"
		puestosofertados = "Gewünschte Positionen"
		lugarescolocacion = "Bestimmungsland"
		edadestudiantes = "Alter der Kursteilnehmer"
		alumnosclase = "Kursteilnehmer durch Kategorie"
		comentarios = "Anmerkungen"
		datospersonales = "Persönliche Daten"
		fechainicio = "Beginn"
		duracion = "Dauer"
		remuneracion = "Vergütung"
		alojamiento = "Unterkunft"
		requisitos = "Anforderungen"
		deseomasinfo = "Ich wünsche, Informationen über Euro-Practice und ihre Angebote zu erhalten."
		irportada = "Home"
		ultimasofertas = "Neueste Angebote"
		ultimasofertas2 = "Neueste Angebote"
		ultimasofertas3 = "Neueste Angebote"
		nosecciones = "No hay secciones"
		textobuscar = "Suchwort"
		vertodas = "Alle"
		listadocompleto = "Komplette Liste"
		seltipotra = "Wählen Sie eine Branche"
		selpais = "Wählen Sie ein Land"

		sehanencontrado = "Gefunden"
		sehanencontrado2 = "Resultate in der Suche nach"
		de = "von"
		fuente = "Quelle"
		
		pagina = "Seite"
		paginas = "Seiten"
		sabermas = "Mehr Info"
		sinresultados = "<b>Leider gibt es keine passenden Ergebnisse.</b>"
		
		espana = "Spanien"
		portugal = "Portugal"
		francia = "Frankreich"
		alemania = "Deutschland"
		irlanda = "Irland"
		reinounido = "Grossbritannien"
		inglaterra = "England"
		escocia = "Schottland"
		austria = "Österreich"
		italia = "Italien"
		
		espamol = "Spanisch"
		ingles = "Englisch"
		frances = "Französisch"
		aleman = "German"
	end select
	Lang = eval(str)
end function

%>